### ISSUE TITLE
SoT tutorials outdated?

### ISSUE THREAD

**Issue by Lichor8** [stack-of-tasks/stack-of-tasks.github.com#4]
Dear all,

After installing sot-v3 on Ubuntu 16.04 I tried to follow [the tutorial](https://stack-of-tasks.github.io/tutorials/b_getting_started.html) to get started with the SoT framework. However, the tutorial seems outdated. The first link towards, I presume the old installation instructions, is broken. I also think the same applies to [this tutorial](https://stack-of-tasks.github.io/tutorials/e_add_your_robot.html).

So in an effort to still work with the tutorial I installed the sot-romeo and romeo-description packages from the apt robotpkg-sot- repository. In doing so sot-v3 was replaced with sot. Now I was able to run the kine_romeo.py tutorial script with a few errors I could correct. From openrobots/lib/python2.7/site-packages/dynamic-graph/tutorials (not a 100% sure about the exact path, not in Ubuntu at the moment). However, it seems that other files (robot.py) were also changed, which meant that the Robot class did not have a "tasks" function anymore and there was no visualization in rviz. So this is where I got stuck.

I would like to get more familiar with this software in order to use it for my Master's Thesis. I am working on optimization-based whole body motion control for a humanoid-like robot (it has a mobile base). Could you suggest a place on where to start, especially about implementing the QP optimization part, if tutorials are unavailable? I did notice that Pinocchio has its own tutorials, so that will be helpful. Or is TSID repository from SoT a good place to look? 

Or a working example using sot-v3, a QP controller/solver and visualization of any one of your humanoids or a robot arm would be very helpful to get me started.

Thank you,
Rik

Ps: I noticed some more broken links on the website, if you like I could submit more issues?

**Comment by nim65s** [comment]
Hi Rik,

Thanks for your tries and your repport.
You are right, the tutorials are outdated and broken.

One of the reasons behind this is that we are not using Romeo anymore, and while the model of Talos is supposed to be opened by pal-robotics, we are still lacking a clean license before being able to distribute easy-to use binary packages with robotpkg.

Meanwhile, @olivier-stasse can provide you a script to install everything with ROS.

**Comment by Lichor8** [comment]
Hi Guilhem,

Should I send Olivier Stasse an email notifying him about this issue or does he automatically receive a notification?

Thank you,
Rik

**Comment by NoePity2** [comment]
Dear all,

Following the line of these comments. I'm going to start following the tutorials and I see that there are two versions of sot core (sot-core and sot-core-v3). Which version do you recommend to start the tutorials?

Regards,

Noe

**Comment by olivier-stasse** [comment]
sot-core-v3 is definitely the one to use.
I am currently updating the tutorials and this version with romeo is outdated.
I will try to post a version with the TALOS robot today as PAL-Robotics kindly changed its license file.

**Comment by NoePity2** [comment]
Thank you very much for the version the TALOS.  I will wait with enthusiasm for the new version of the tutorials in order to continue learning the use of this software.

Regards,

**Comment by olivier-stasse** [comment]
Dear @NoePity2 
Sorry for the late reply. The first tutorial has been updated.
http://stack-of-tasks.github.io/tutorials/b_getting_started.html
We checked that the binary packages are working.
We were delayed with the new kinetic release.

I will try to give instructions to make a source installation.
Wrt to current control, the current version has some default, and we hope to give something build upon sot-torque-control and tsid in the following weeks.

Thanks for your feedback.
Best,
Olivier.

**Comment by NoePity2** [comment]
Dear @olivier-stasse 
Thanks for updating the tutorials. When I was following the steps of the tutorial, the following message appeared on the console:

_sudo apt-get install robotpkg-sot-talos robotpkg-talos-dev robotpkg-talos-simulation
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package robotpkg-talos-simulation is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'robotpkg-talos-simulation' has no installation candidate_

Is it possible that this package is missing in the repository?

Best,
Noe

**Comment by olivier-stasse** [comment]
I think this has been fixed.

**Comment by olivier-stasse** [comment]
I will close it as many users test the new version and the tutorial has become our integrative test.
